name: CI/CD Pipeline for NodeJS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: self-hosted  # Запуск на вашем ПК
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14'  

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        shell: powershell
        run: |
          if ((Test-Path package.json) -and ((Get-Content package.json | Select-String '"test":'))) {
               npm test
                } else {
                        Write-Output "No tests defined"
                        }



      - name: Deploy Application
        shell: powershell
        run: |
         Get-Process node -ErrorAction SilentlyContinue | ForEach-Object { Stop-Process -Id $_.Id -Force }
         Start-Process -FilePath "node" -ArgumentList "app.js" -NoNewWindow
         
      - name: Open Browser
        shell: powershell
        run: |
          Start-Process -FilePath "chrome.exe" -ArgumentList "--new-window", "http://localhost:80"
          
      - name: Notify Deployment
        run: echo "NodeJS Application deployed successfully!"
